#!/bin/bash
if [ -z "$(ps axo comm |grep handymenu.py)" ]; then
    cd "/usr/share/handymenu"
    ./handymenu.py maxi
else
    echo "Handy-menu est déjà lancé"
    killall handymenu-maxi.py
    cd "/usr/share/handymenu"
    ./handymenu.py maxi
fi

exit 0
